### ISSUE TITLE
dockerfile build 시 시간이 너무 오래 소요 됩니다.

### ISSUE THREAD

**Issue by gyunseo** [skkuse/2023fall_41class_team2#14]
제 local WSL2 기준 400~600s 소요.
apt-get source server에서 package를 갖고 올 때 심한 병목 현상을 보이는 듯합니다.

**Comment by Yanghyeondong** [comment]
혹시 한번 이미지가 빌드 된 이후에도 계속 오래 걸리나요?
저 같은 경우 최초 1번의 빌드 이후로는 딱히 오래 걸린 적이 없어서(이미지가 완성되므로) 크게 문제로 인식하지는 못했습니다.
혹시나 지속적으로 시간이 오래 걸린 것이라면 자세하게 확인해보고 해결할 필요가 있을 것 같습니다!

**Comment by Yanghyeondong** [comment]
캐싱 기능을 쓰다보니 build 시간 단축에 대해서는 크게 생각해보지 못한 것 같습니다.
해당 부분의 속도를 개선할 수 있으면 좋을 것 같습니다!!
