### ISSUE TITLE
backend branch에서 작업하다가, frontend branch로 switch 하면 `backend/app/__pycache__` directory가 resolve되지 않습니다.

### ISSUE THREAD

**Issue by gyunseo** [skkuse/2023fall_41class_team2#15]
`backend/app/__pycache__`가 그대로 local에 남아 있어서, root directory에 .gitignore를 추가해서 resolve해야 할 거 같습니다.

**Comment by ka1dyn** [comment]
말씀해주신대로 gitignore 경로 추가했습니다!!
