### ISSUE TITLE
front에서 backend로 java code를 넘겨줄 때, java code를 format해서 넘겨주기

### ISSUE THREAD

**Issue by gyunseo** [skkuse/2023fall_41class_team2#30]
npm에 [prettier plugin java](https://www.npmjs.com/package/prettier-plugin-java)가 있더라고요. 이걸로 code를 formatting해서 backend로 넘겨줘도 괜찮을 것 같습니다.

**Comment by ka1dyn** [comment]
39번 내용으로 반영되었습니다!
